# NOTE : DONOT run this file unless and until you have replaced
# the values in data section with the appropriate ones

apiVersion: v1
kind: Secret
metadata:
  name: pollsapi-static-serve
data:
  gs_access_key_id: R09PR1JIQ1UzRTRIQVRMNVlMWjY1NDNZ
  gs_secret_access_key: VzVIWjNoS2REZDI3V01NZUdna0NpTmFxaVJEVnk5azE3aGxoemVmWQ==
  gs_bucket_name: c2hvcG5ldC1idWNrZXQ=
