# Generated by Django 2.0.6 on 2018-09-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopnet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='buyer',
        ),
    ]
