# Generated by Django 2.0.6 on 2018-09-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopnet', '0002_remove_ordermodel_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitemmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='buyer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
