# Generated by Django 2.0.6 on 2018-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopnet', '0003_auto_20180912_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='buyer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
